site_name: AvaInsta

theme: 
  name: material

nav:
  - Home: index.md
  - Documentos:
    - Visão do Projeto: Visao_do_projeto.pdf
    - Product BackLog: product-backlog.md
    - Arquitetura: documento_de_arquitetura.md
    - Identidade Visual do produto: 
      - Baixa Fidelidade: baixa_fidelidade.md
      - Identidade Visual: documento_de_identidade_visual.md
    - Estratégia de Testes: Estrategia_de_testes.pdf
  - Sprints:
    - Sprint00:
      - planning: sprints/sprint00/Planning.md
      - Results: sprints/sprint00/Results.md
    - Sprint01:
      - planning: sprints/sprint01/planning.md
    - Sprint02:
      - planning: sprints/sprint02/planning.md
    - Sprint03:
      - planning: sprints/sprint03/planning.md
    - Sprint04:
      - planning: sprints/sprint04/planning.md


extra_css:
- "style/home.css"