site_name: AvaInsta

theme: 
  name: material

nav:
  - Home: index.md
  - Documentos:
    - Visão do Projeto: Visao_do_projeto.pdf
    - Product BackLog: product-backlog.md
    - Arquitetura: documento_de_arquitetura.md
    - Prototipos: 
      - Baixa Fidelidade: baixa_fidelidade.md
  - Sprints:
    - Sprint00:
      - planning: sprints/sprint00/Planning.md
      - Results: sprints/sprint00/Results.md
    - Sprint01:
      - planning: sprints/sprint01/planning.md


extra_css:
- "style/home.css"